<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use App\Models\Item;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // --- 既有貿易／生活物資 ---
            [
                'name' => '武夷茶葉',
                'description' => '來自福建武夷山的岩茶，茶香濃郁，是士大夫與洋商的最愛。',
                'type' => 'luxury',
                'unit' => '斤',
                'image_path' => 'images/items/tea.jpg',
                'base_price' => 300,
                'stock' => 500,
                'target_stock' => 500,
                'volatility' => 0.8,
            ],
            [
                'name' => '稻米',
                'description' => '東寧平原開墾所產的糧食，顆粒飽滿，是百姓與軍隊的根本。',
                'type' => 'food',
                'unit' => '斤',
                'image_path' => 'images/items/rice.jpg',
                'base_price' => 50,
                'stock' => 2000,
                'target_stock' => 2000,
                'volatility' => 1.5,
            ],
            [
                'name' => '陶瓷水甕',
                'description' => '燒製厚實的陶甕，能長時間保存淡水不變質，航海必備。',
                'type' => 'equipment',
                'unit' => '罐',
                'image_path' => 'images/items/pottery.jpg',
                'base_price' => 120,
                'stock' => 800,
                'target_stock' => 800,
                'volatility' => 0.3,
            ],
            [
                'name' => '木桶水槽',
                'description' => '用堅硬杉木箍成的巨大水槽，用於船上儲存洗刷用水或救火。',
                'type' => 'equipment',
                'unit' => '桶',
                'image_path' => 'images/items/barrel.jpg',
                'base_price' => 200,
                'stock' => 400,
                'target_stock' => 400,
                'volatility' => 0.4,
            ],
            [
                'name' => '臘肉',
                'description' => '以鹽與香料醃製後風乾的肉條，便於攜帶且能久放。',
                'type' => 'food',
                'unit' => '斤',
                'image_path' => 'images/items/meat.jpg',
                'base_price' => 80,
                'stock' => 1000,
                'target_stock' => 1000,
                'volatility' => 0.6,
            ],
            [
                'name' => '白酒',
                'description' => '烈性高粱酒，不僅能驅寒，戰時還能用來消毒傷口。',
                'type' => 'luxury',
                'unit' => '瓶',
                'image_path' => 'images/items/wine.jpg',
                'base_price' => 150,
                'stock' => 600,
                'target_stock' => 600,
                'volatility' => 0.5,
            ],

            // --- 基礎原料（採集／種植／貿易）---
            [
                'name' => '竹子',
                'description' => '販客採集易得。基礎造船、竹篾編織、小型武器骨架皆離不開它。',
                'type' => 'material',
                'unit' => '捆',
                'image_path' => 'images/items/竹子.jpg',
                'base_price' => 18,
                'min_price' => 8,
                'max_price' => 55,
                'stock' => 3500,
                'target_stock' => 3500,
                'volatility' => 0.45,
            ],
            [
                'name' => '相思木',
                'description' => '販客採集。質堅耐潮，常用於船隻龍骨、硬木零件與薪材。',
                'type' => 'material',
                'unit' => '段',
                'image_path' => 'images/items/相思木.jpg',
                'base_price' => 48,
                'min_price' => 18,
                'max_price' => 140,
                'stock' => 1800,
                'target_stock' => 1800,
                'volatility' => 0.55,
            ],
            [
                'name' => '樟木',
                'description' => '販客於中低海拔採集。適合中大型船身、防蟲家具與外銷硬木貨。',
                'type' => 'material',
                'unit' => '段',
                'image_path' => 'images/items/樟木.jpg',
                'base_price' => 95,
                'min_price' => 35,
                'max_price' => 280,
                'stock' => 1200,
                'target_stock' => 1200,
                'volatility' => 0.5,
            ],
            [
                'name' => '紅檜',
                'description' => '販客與部落於高海拔貿易取得。傳說級船骨、高級營建與王府軍用工料。',
                'type' => 'material',
                'unit' => '板',
                'image_path' => 'images/items/紅檜.jpg',
                'base_price' => 420,
                'min_price' => 150,
                'max_price' => 1200,
                'stock' => 200,
                'target_stock' => 200,
                'volatility' => 0.85,
            ],
            [
                'name' => '薯榔',
                'description' => '販客採集。可製帆布染料，亦為藥材與染整工藝的重要原料。',
                'type' => 'material',
                'unit' => '斤',
                'image_path' => 'images/items/薯榔.jpg',
                'base_price' => 28,
                'min_price' => 10,
                'max_price' => 85,
                'stock' => 2200,
                'target_stock' => 2200,
                'volatility' => 0.55,
            ],
            [
                'name' => '苧麻',
                'description' => '屯墾兵種植或販客收購。織布與粗繩製作的核心纖維作物。',
                'type' => 'material',
                'unit' => '斤',
                'image_path' => 'images/items/苧麻.jpg',
                'base_price' => 38,
                'min_price' => 14,
                'max_price' => 110,
                'stock' => 2000,
                'target_stock' => 2000,
                'volatility' => 0.5,
            ],
            [
                'name' => '甘蔗',
                'description' => '屯墾兵種植。煉製白糖與糖貿易的基礎原料。',
                'type' => 'material',
                'unit' => '斤',
                'image_path' => 'images/items/甘蔗.jpg',
                'base_price' => 20,
                'min_price' => 8,
                'max_price' => 60,
                'stock' => 2800,
                'target_stock' => 2800,
                'volatility' => 0.55,
            ],
            [
                'name' => '硫磺',
                'description' => '販客經北投、卑南等地貿易取得。火藥與軍用工藝的關鍵礦料。',
                'type' => 'material',
                'unit' => '斤',
                'image_path' => 'images/items/硫磺.jpg',
                'base_price' => 130,
                'min_price' => 45,
                'max_price' => 380,
                'stock' => 450,
                'target_stock' => 450,
                'volatility' => 0.7,
            ],
            [
                'name' => '鹿皮',
                'description' => '販客與原民貿易而來。高價值外銷皮貨，長崎洋行常指名收購。',
                'type' => 'luxury',
                'unit' => '張',
                'image_path' => 'images/items/鹿皮.jpg',
                'base_price' => 360,
                'min_price' => 120,
                'max_price' => 980,
                'stock' => 180,
                'target_stock' => 180,
                'volatility' => 0.75,
            ],
            [
                'name' => '蚵仔',
                'description' => '屯墾兵養殖。鮮食可恢復體力，亦是特殊飾品合成的海濱材料。',
                'type' => 'food',
                'unit' => '斤',
                'image_path' => 'images/items/蚵仔.jpg',
                'base_price' => 26,
                'min_price' => 10,
                'max_price' => 75,
                'stock' => 1600,
                'target_stock' => 1600,
                'volatility' => 0.65,
            ],
            [
                'name' => '薄荷',
                'description' => '山野常見清涼香草。可入藥、提香，為配製清涼散的材料之一。',
                'type' => 'material',
                'unit' => '斤',
                'image_path' => 'images/items/薄荷.jpg',
                'base_price' => 24,
                'min_price' => 9,
                'max_price' => 72,
                'stock' => 1400,
                'target_stock' => 1400,
                'volatility' => 0.6,
            ],

            // --- 外購／採集補位（合成配方用，系統稍後實作）---
            [
                'name' => '硝石',
                'description' => '多購自英商船貨。與硫磺調配為火藥。合成配方（待系統）：硫磺×2＋硝石×1。',
                'type' => 'material',
                'unit' => '斤',
                'image_path' => 'images/items/硝石.jpg',
                'base_price' => 210,
                'min_price' => 70,
                'max_price' => 600,
                'stock' => 320,
                'target_stock' => 320,
                'volatility' => 0.8,
            ],
            [
                'name' => '特殊草藥',
                'description' => '採藥人於林野搜集的配伍用料。合成配方（待系統）：傷藥需薯榔×1＋特殊草藥×2；清涼散需特殊草藥×2＋薄荷×1。',
                'type' => 'material',
                'unit' => '把',
                'image_path' => 'images/items/一般草藥.jpg',
                'base_price' => 42,
                'min_price' => 15,
                'max_price' => 125,
                'stock' => 900,
                'target_stock' => 900,
                'volatility' => 0.55,
            ],

            // --- 加工半成品（Intermediate）---
            [
                'name' => '竹篾',
                'description' => '竹工剖篾而成。合成配方（待系統）：竹子×1。用於船帆骨架與簡易船裝。',
                'type' => 'material',
                'unit' => '捆',
                'image_path' => 'images/items/竹篾.jpg',
                'base_price' => 28,
                'min_price' => 10,
                'max_price' => 85,
                'stock' => 800,
                'target_stock' => 800,
                'volatility' => 0.45,
            ],
            [
                'name' => '苧麻布',
                'description' => '織工將苧麻紡織成布。合成配方（待系統）：苧麻×3。造船帆裝與中階貿易貨。',
                'type' => 'material',
                'unit' => '匹',
                'image_path' => 'images/items/苧麻布.jpg',
                'base_price' => 135,
                'min_price' => 48,
                'max_price' => 380,
                'stock' => 500,
                'target_stock' => 500,
                'volatility' => 0.5,
            ],
            [
                'name' => '單寧染劑',
                'description' => '由薯榔萃取濃縮。合成配方（待系統）：薯榔×3。供染布與帆布著色。',
                'type' => 'material',
                'unit' => '罐',
                'image_path' => 'images/items/單寧染劑.jpg',
                'base_price' => 98,
                'min_price' => 35,
                'max_price' => 290,
                'stock' => 400,
                'target_stock' => 400,
                'volatility' => 0.5,
            ],
            [
                'name' => '薯榔染布',
                'description' => '苧麻布經薯榔單寧染整後的耐曬帆布。合成配方（待系統）：苧麻布×1＋單寧染劑×1。',
                'type' => 'material',
                'unit' => '匹',
                'image_path' => 'images/items/薯榔染布.jpg',
                'base_price' => 265,
                'min_price' => 95,
                'max_price' => 780,
                'stock' => 280,
                'target_stock' => 280,
                'volatility' => 0.55,
            ],
            [
                'name' => '白糖',
                'description' => '糖寮熬煮甘蔗結晶而成。合成配方（待系統）：甘蔗×5。',
                'type' => 'material',
                'unit' => '斤',
                'image_path' => 'images/items/白糖.jpg',
                'base_price' => 125,
                'min_price' => 45,
                'max_price' => 360,
                'stock' => 600,
                'target_stock' => 600,
                'volatility' => 0.55,
            ],
            [
                'name' => '火藥',
                'description' => '軍工匠調配。合成配方（待系統）：硫磺×2＋硝石×1（硝石多購自英商）。',
                'type' => 'equipment',
                'unit' => '斤',
                'image_path' => 'images/items/火藥.jpg',
                'base_price' => 420,
                'min_price' => 150,
                'max_price' => 1100,
                'stock' => 200,
                'target_stock' => 200,
                'volatility' => 0.75,
            ],
            [
                'name' => '傷藥',
                'description' => '軍醫與草藥郎配伍。合成配方（待系統）：薯榔×1＋特殊草藥×2。',
                'type' => 'equipment',
                'unit' => '包',
                'image_path' => 'images/items/傷藥.jpg',
                'base_price' => 88,
                'min_price' => 30,
                'max_price' => 260,
                'stock' => 700,
                'target_stock' => 700,
                'volatility' => 0.45,
            ],
            [
                'name' => '清涼散',
                'description' => '解暑提神成藥。合成配方（待系統）：特殊草藥×2＋薄荷×1。',
                'type' => 'equipment',
                'unit' => '包',
                'image_path' => 'images/items/清涼散.jpg',
                'base_price' => 102,
                'min_price' => 35,
                'max_price' => 300,
                'stock' => 650,
                'target_stock' => 650,
                'volatility' => 0.45,
            ],

            // --- 造船特材 ---
            [
                'name' => '特選樟木',
                'description' => '挑選紋理與油脂俱佳的樟木大料，供東寧龍首號等頂級船體肋骨與艙壁。',
                'type' => 'material',
                'unit' => '段',
                'image_path' => 'images/items/特選樟木.jpg',
                'base_price' => 380,
                'min_price' => 130,
                'max_price' => 1050,
                'stock' => 120,
                'target_stock' => 120,
                'volatility' => 0.65,
            ],
            [
                'name' => '特製混紡帆',
                'description' => '苧麻、竹纖與薯榔染紗混紡加密的遠洋帆，為東寧龍首號指定帆裝。圖檔待補時可於後台上傳。',
                'type' => 'material',
                'unit' => '面',
                'image_path' => 'images/items/特製混紡帆.jpg',
                'base_price' => 820,
                'min_price' => 280,
                'max_price' => 2200,
                'stock' => 40,
                'target_stock' => 40,
                'volatility' => 0.55,
            ],

            // --- 五級船隻（設計需求備註，造船系統稍後實作）---
            [
                'name' => '竹篾雙帆船',
                'description' => '入門級雙桅快船。設計需求（待系統）：竹子×10、相思木×2；竹篾×2。航線：思明州、濠鏡。',
                'type' => 'equipment',
                'unit' => '艘',
                'image_path' => 'images/items/竹篾雙帆船.jpg',
                'base_price' => 4800,
                'min_price' => 1800,
                'max_price' => 14000,
                'stock' => 25,
                'target_stock' => 25,
                'volatility' => 0.5,
            ],
            [
                'name' => '苧麻赤木船',
                'description' => '硬木船體配苧麻帆裝的中型商船。設計需求（待系統）：相思木×15、樟木×5；苧麻布×3。航線：東洋、長崎。',
                'type' => 'equipment',
                'unit' => '艘',
                'image_path' => 'images/items/苧麻赤木船.jpg',
                'base_price' => 12500,
                'min_price' => 4800,
                'max_price' => 36000,
                'stock' => 15,
                'target_stock' => 15,
                'volatility' => 0.48,
            ],
            [
                'name' => '薯榔闊嘴船',
                'description' => '寬艙闊嘴利於南洋散貨。設計需求（待系統）：樟木×25、竹子×10；薯榔染布×4。航線：暹羅、馬尼拉。',
                'type' => 'equipment',
                'unit' => '艘',
                'image_path' => 'images/items/薯榔闊嘴船.jpg',
                'base_price' => 29000,
                'min_price' => 11000,
                'max_price' => 82000,
                'stock' => 8,
                'target_stock' => 8,
                'volatility' => 0.45,
            ],
            [
                'name' => '檜骨大戎克',
                'description' => '紅檜龍骨配重武装貨艙的遠洋戎克。設計需求（待系統）：紅檜×10、樟木×30；薯榔染布×6、火藥×5。航線：爪哇、英圭黎。',
                'type' => 'equipment',
                'unit' => '艘',
                'image_path' => 'images/items/檜骨大戎克.jpg',
                'base_price' => 88000,
                'min_price' => 33000,
                'max_price' => 240000,
                'stock' => 4,
                'target_stock' => 4,
                'volatility' => 0.42,
            ],
            [
                'name' => '東寧龍首號',
                'description' => '造船者終極目標。設計需求（待系統）：紅檜×30、特選樟木×20；特製混紡帆×8。傳說可開啟全圖貿易航線。',
                'type' => 'equipment',
                'unit' => '艘',
                'image_path' => 'images/items/東寧龍首號.jpg',
                'base_price' => 225000,
                'min_price' => 85000,
                'max_price' => 580000,
                'stock' => 1,
                'target_stock' => 1,
                'volatility' => 0.35,
            ],
        ];

        // 首次建立才寫入經濟欄位（基價、庫存、波動等）；已存在的列只同步文案／分類／圖，
        // 避免重跑 seeder 或部署時覆蓋遊戲中已演化的市場狀態。
        foreach ($items as $item) {
            $record = Item::firstOrCreate(['name' => $item['name']], $item);

            if (! $record->wasRecentlyCreated) {
                $record->update(Arr::only($item, [
                    'description',
                    'type',
                    'unit',
                    'image_path',
                ]));
            }
        }
    }
}
